apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-platform-task
  labels:
    app: cloud-platform-task
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloud-platform-task
  template:
    metadata:
      labels:
        app: cloud-platform-task
    spec:
      containers:
        - name: cloud-platform-task
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10